volumes:
  maven-repository:
  
services:
  app:
    container_name: dio
    image: ms-java21
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      - "../..:/workspaces:cached"
      - "./configs/maven/settings.xml:/usr/local/sdkman/candidates/maven/current/conf/settings.xml"
      - "${SSH_HOME}:/home/vscode/.ssh"
      - "maven-repository:/var/maven/.m2"
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

